language: php

sudo: false

php:
  - 7.1

services:
  - mysql
  - redis-server

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - mysql -e 'create database wdipastes;'
  - chmod 777 -R storage
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate:fresh --seed

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: setup=stable

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - printf "\n" | pecl install -f redis
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --dev --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer install --dev --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'edgy' ]]; then travis_retry composer install --dev --prefer-dist --no-interaction --prefer-lowest --no-suggest; fi

script: vendor/bin/phpunit

notifications:
  email: false
