language: php

sudo: false

php:
  - 7.1

env:
  global:
    - setup=basic

services:
  - mysql
  - redis-server

before_script:
  - mysql -e 'create database wdipastes;'
  - chmod 777 -R storage
  - cp .env.travis .env
  - php artisan key:generate

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: setup=stable

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - printf "\n" | pecl install -f redis
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'edgy' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit
