language: php

php:
  - 7.1
  - 7.2

env:
  global:
    - setup=basic

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: setup=stable
    - php: 7.2
      env: setup=edgy

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server

before_install:
  - printf "\n" | pecl install -f redis
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'edgy' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit
